const token = (name) => `var(${name})`;

/** @type {import('tailwindcss').Config} */
export default {
  content: ["./index.html", "./src/**/*.{ts,tsx}"],
  darkMode: "media",
  theme: {
    extend: {
      colors: {
        primary: token("--color-primary"),
        success: token("--color-success"),
        warning: token("--color-warning"),
        danger: token("--color-danger"),
        muted: token("--color-muted"),
        bg: token("--color-bg"),
        text: token("--color-text"),
        surface: "#FFFFFF",
        surfaceMuted: "#F7F7F9",
        surfaceDark: "#0F1116",
        border: "rgba(0,0,0,0.10)",
        borderDark: "rgba(255,255,255,0.12)",
        textMuted: "#6B7280",
        background: "rgb(var(--background) / <alpha-value>)",
        foreground: "rgb(var(--foreground) / <alpha-value>)",
        card: "rgb(var(--card) / <alpha-value>)",
        "card-foreground": "rgb(var(--card-foreground) / <alpha-value>)",
        popover: "rgb(var(--popover) / <alpha-value>)",
        "popover-foreground": "rgb(var(--popover-foreground) / <alpha-value>)",
        secondary: "rgb(var(--secondary) / <alpha-value>)",
        "secondary-foreground": "rgb(var(--secondary-foreground) / <alpha-value>)",
        accent: "rgb(var(--accent) / <alpha-value>)",
        "accent-foreground": "rgb(var(--accent-foreground) / <alpha-value>)",
        destructive: "rgb(var(--destructive) / <alpha-value>)",
        "destructive-foreground": "rgb(var(--destructive-foreground) / <alpha-value>)",
        ring: "rgb(var(--ring) / <alpha-value>)",
      },
      spacing: {
        xs: "4px",
        sm: "8px",
        md: "16px",
        lg: "24px",
      },
      borderRadius: {
        sm: "8px",
        md: "12px",
        lg: "16px",
      },
      boxShadow: {
        subtle: "0 1px 2px rgba(0,0,0,0.06)",
        card: "0 2px 8px rgba(0,0,0,0.10)",
      },
      zIndex: {
        header: "40",
        toolbar: "45",
        overlay: "80",
        modal: "90",
      },
      fontFamily: {
        sans: [
          "ui-sans-serif",
          "system-ui",
          "-apple-system",
          "Segoe UI",
          "Roboto",
          "Helvetica Neue",
          "Arial",
          "Noto Sans",
          "Apple Color Emoji",
          "Segoe UI Emoji",
        ],
      },
    },
  },
  plugins: [],
};
